{{- if and .Values.backend.enabled .Values.backend.createServiceAccount .Values.backend.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pm-journey.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.backend.serviceAccountAnnotations }}
  annotations:
    {{- toYaml .Values.backend.serviceAccountAnnotations | nindent 4 }}
  {{- end }}
{{- end }}
