{{- if and .Values.backend.enabled .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pm-journey.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "pm-journey.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.backend.ingress.className }}
  ingressClassName: {{ .Values.backend.ingress.className | quote }}
  {{- end }}
  {{- if .Values.backend.ingress.tls }}
  tls:
    {{- toYaml .Values.backend.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.backend.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "pm-journey.fullname" $ }}-backend
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
