global:
  domain: "staging.pm-journey.com"

frontend:
  replicaCount: 2
  image:
    tag: staging
  ingress:
    hosts:
      - host: "app.staging.pm-journey.com"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: staging-frontend-tls
        hosts:
          - "app.staging.pm-journey.com"

backend:
  replicaCount: 2
  image:
    tag: staging
  secretEnv:
    - name: DATABASE_URL
      secretName: staging-backend-database
      secretKey: DATABASE_URL
