global:
  domain: "pm-journey.com"

frontend:
  replicaCount: 3
  image:
    tag: prod
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 2
      memory: 512Mi
  ingress:
    hosts:
      - host: "app.pm-journey.com"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: prod-frontend-tls
        hosts:
          - "app.pm-journey.com"

backend:
  replicaCount: 3
  image:
    tag: prod
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 1Gi
  secretEnv:
    - name: DATABASE_URL
      secretName: prod-backend-database
      secretKey: DATABASE_URL
    - name: AZURE_CLIENT_ID
      secretName: prod-backend-msi
      secretKey: clientId
    - name: AZURE_TENANT_ID
      secretName: prod-backend-msi
      secretKey: tenantId
    - name: AZURE_FEDERATED_TOKEN_FILE
      secretName: prod-backend-msi
      secretKey: federatedTokenFile
